name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build the site

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '19.8.1', latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run TSC
      run: npm run typecheck
    - name: Build
      run: npm run build

  lint:
    name: Check code standards

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 19.8.1
      uses: actions/setup-node@v3
      with:
        node-version: '19.8.1'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint

    
